version: "3.9"

services:
  app:
    build: .
    container_name: django
    restart: always
    env_file:
      - django.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: make setup_and_run

  nginx:
    image: nginx:1.23-alpine
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
