# Generated by Django 5.0.6 on 2024-06-03 16:47

import django.core.validators
import qr.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('media_file', models.FileField(blank=True, help_text='Загрузите файл изображения или видео (не более 2,5 минут)', null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'mp4', 'avi', 'mkv', 'mov']), qr.validators.validate_video_duration], verbose_name='Медиафайл')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Открытка',
                'verbose_name_plural': 'Открытки',
            },
        ),
    ]
