# Generated by Django 5.0.6 on 2024-05-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_compressing',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
