# Generated by Django 5.0.6 on 2024-05-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0004_remove_card_is_compressing_card_compression_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='compression_task_id',
        ),
    ]
