# Generated by Django 5.0.6 on 2024-06-03 15:24

import django.core.validators
import qr.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0005_remove_card_compression_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='card',
            name='media_file',
            field=models.FileField(blank=True, help_text='Загрузите файл изображения или видео (не более 2,5 минут)', null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'mp4', 'avi', 'mkv', 'mov']), qr.validators.validate_video_duration], verbose_name='Медиафайл'),
        ),
    ]
